# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170316_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_modify',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_publish',
            field=models.DateTimeField(verbose_name='发布日期'),
        ),
    ]
